"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from .functionobject import FunctionObject
from dataclasses_json import Undefined, dataclass_json
from enum import Enum
from log10 import utils


class ChatCompletionToolType(str, Enum):
    r"""The type of the tool. Currently, only `function` is supported."""
    FUNCTION = 'function'


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class ChatCompletionTool:
    type: ChatCompletionToolType = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('type') }})
    r"""The type of the tool. Currently, only `function` is supported."""
    function: FunctionObject = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('function') }})
    

