"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .chatcompletionrequestmessagecontentpartimage import ChatCompletionRequestMessageContentPartImage
from .chatcompletionrequestmessagecontentparttext import ChatCompletionRequestMessageContentPartText
from typing import Union

ChatCompletionRequestMessageContentPart = Union[ChatCompletionRequestMessageContentPartText, ChatCompletionRequestMessageContentPartImage]
